version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/parser"
    versions:
    - 7.12.13
    - 7.12.15
    - 7.12.16
    - 7.13.0
    - 7.13.10
    - 7.13.11
    - 7.13.12
    - 7.13.13
    - 7.13.15
    - 7.13.4
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.8
  - dependency-name: webpack
    versions:
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
