language: node_js
cache: false
sudo: required
script:
  - npm test
branches:
  only:
    - master
before_install:
  - docker pull selenium/standalone-chrome:3.8.1-erbium
  - docker run -v /dev/shm:/dev/shm -e TZ=America/Chicago -d -p 4444:4444 selenium/standalone-chrome:3.8.1-erbium
before_deploy:
  - npm run build:production
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master
