language: node_js
cache: false
sudo: required
script:
  - npm test
branches:
  only:
    - master
before_deploy:
  - npm run build:production
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master
