/* This file is auto-generated by terra-dev-site's generate-component-config config. */

// Component Examples
import TerraClinicalIndex from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/action-header/Index';
import TerraClinicalIndex1 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/application/Index';
import TerraClinicalIndex2 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/detail-view/Index';
import TerraClinicalIndex3 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/error-view/Index';
import TerraClinicalIndex4 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/header/Index';
import TerraClinicalIndex5 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/item-collection/Index';
import TerraClinicalIndex6 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/item-display/Index';
import TerraClinicalIndex7 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/item-view/Index';
import TerraClinicalIndex8 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/label-value-view/Index';
import TerraClinicalIndex9 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/no-data-view/Index';
import TerraClinicalIndex10 from './node_modules/terra-clinical/packages/terra-clinical-site/src/examples/onset-picker/Index';
import TerraCoreIndex from './node_modules/terra-core/packages/terra-site/src/examples/alert/Index';
import TerraCoreIndex1 from './node_modules/terra-core/packages/terra-site/src/examples/arrange/Index';
import TerraCoreIndex2 from './node_modules/terra-core/packages/terra-site/src/examples/badge/Index';
import TerraCoreIndex3 from './node_modules/terra-core/packages/terra-site/src/examples/base/Index';
import TerraCoreIndex4 from './node_modules/terra-core/packages/terra-site/src/examples/button-group/Index';
import TerraCoreIndex5 from './node_modules/terra-core/packages/terra-site/src/examples/button/Index';
import TerraCoreIndex6 from './node_modules/terra-core/packages/terra-site/src/examples/card/Index';
import TerraCoreIndex7 from './node_modules/terra-core/packages/terra-site/src/examples/collapsible-menu-view/Index';
import TerraCoreIndex8 from './node_modules/terra-core/packages/terra-site/src/examples/content-container/Index';
import TerraCoreIndex9 from './node_modules/terra-core/packages/terra-site/src/examples/date-picker/Index';
import TerraCoreIndex10 from './node_modules/terra-core/packages/terra-site/src/examples/date-time-picker/Index';
import TerraCoreIndex11 from './node_modules/terra-core/packages/terra-site/src/examples/demographics-banner/Index';
import TerraCoreIndex12 from './node_modules/terra-core/packages/terra-site/src/examples/dialog/Index';
import TerraCoreIndex13 from './node_modules/terra-core/packages/terra-site/src/examples/divider/Index';
import TerraCoreIndex14 from './node_modules/terra-core/packages/terra-site/src/examples/dynamic-grid/Index';
import TerraCoreIndex15 from './node_modules/terra-core/packages/terra-site/src/examples/embedded-content-consumer/Index';
import TerraCoreIndex16 from './node_modules/terra-core/packages/terra-site/src/examples/form-checkbox/Index';
import TerraCoreIndex17 from './node_modules/terra-core/packages/terra-site/src/examples/form-field/Index';
import TerraCoreIndex18 from './node_modules/terra-core/packages/terra-site/src/examples/form-input/Index';
import TerraCoreIndex19 from './node_modules/terra-core/packages/terra-site/src/examples/form-radio/Index';
import TerraCoreIndex20 from './node_modules/terra-core/packages/terra-site/src/examples/form-select/Index';
import TerraCoreIndex21 from './node_modules/terra-core/packages/terra-site/src/examples/form-textarea/Index';
import TerraCoreIndex22 from './node_modules/terra-core/packages/terra-site/src/examples/form/Index';
import TerraCoreIndex23 from './node_modules/terra-core/packages/terra-site/src/examples/grid/Index';
import TerraCoreIndex24 from './node_modules/terra-core/packages/terra-site/src/examples/heading/Index';
import TerraCoreIndex25 from './node_modules/terra-core/packages/terra-site/src/examples/hookshot/Index';
import TerraCoreIndex26 from './node_modules/terra-core/packages/terra-site/src/examples/i18n/Index';
import TerraCoreIndex27 from './node_modules/terra-core/packages/terra-site/src/examples/icon/Index';
import TerraCoreIndex28 from './node_modules/terra-core/packages/terra-site/src/examples/image/Index';
import TerraCoreIndex29 from './node_modules/terra-core/packages/terra-site/src/examples/list/Index';
import TerraCoreIndex30 from './node_modules/terra-core/packages/terra-site/src/examples/menu/Index';
import TerraCoreIndex31 from './node_modules/terra-core/packages/terra-site/src/examples/modal/Index';
import TerraCoreIndex32 from './node_modules/terra-core/packages/terra-site/src/examples/overlay/Index';
import TerraCoreIndex33 from './node_modules/terra-core/packages/terra-site/src/examples/popup/Index';
import TerraCoreIndex34 from './node_modules/terra-core/packages/terra-site/src/examples/profile-image/Index';
import TerraCoreIndex35 from './node_modules/terra-core/packages/terra-site/src/examples/progress-bar/Index';
import TerraCoreIndex36 from './node_modules/terra-core/packages/terra-site/src/examples/responsive-element/Index';
import TerraCoreIndex37 from './node_modules/terra-core/packages/terra-site/src/examples/search-field/Index';
import TerraCoreIndex38 from './node_modules/terra-core/packages/terra-site/src/examples/signature/Index';
import TerraCoreIndex39 from './node_modules/terra-core/packages/terra-site/src/examples/slide-group/Index';
import TerraCoreIndex40 from './node_modules/terra-core/packages/terra-site/src/examples/slide-panel/Index';
import TerraCoreIndex41 from './node_modules/terra-core/packages/terra-site/src/examples/spacer/Index';
import TerraCoreIndex42 from './node_modules/terra-core/packages/terra-site/src/examples/status-view/Index';
import TerraCoreIndex43 from './node_modules/terra-core/packages/terra-site/src/examples/status/Index';
import TerraCoreIndex44 from './node_modules/terra-core/packages/terra-site/src/examples/table/Index';
import TerraCoreIndex45 from './node_modules/terra-core/packages/terra-site/src/examples/tabs/Index';
import TerraCoreIndex46 from './node_modules/terra-core/packages/terra-site/src/examples/text/Index';
import TerraCoreIndex47 from './node_modules/terra-core/packages/terra-site/src/examples/time-input/Index';
import TerraCoreIndex48 from './node_modules/terra-core/packages/terra-site/src/examples/toggle-button/Index';
import TerraCoreIndex49 from './node_modules/terra-core/packages/terra-site/src/examples/toggle/Index';
import TerraFrameworkIndex from './node_modules/terra-framework/packages/terra-aggregator/examples/Index.site-page';
import TerraFrameworkIndex1 from './node_modules/terra-framework/packages/terra-app-delegate/examples/Index.site-page';
import TerraFrameworkIndex2 from './node_modules/terra-framework/packages/terra-application-header-layout/examples/Index.site-page';
import TerraFrameworkIndex3 from './node_modules/terra-framework/packages/terra-application-links/examples/Index.site-page';
import TerraFrameworkIndex4 from './node_modules/terra-framework/packages/terra-application-menu-layout/examples/Index.site-page';
import TerraFrameworkIndex5 from './node_modules/terra-framework/packages/terra-application-name/examples/Index.site-page';
import TerraFrameworkIndex6 from './node_modules/terra-framework/packages/terra-disclosure-manager/examples/Index.site-page';
import TerraFrameworkIndex8 from './node_modules/terra-framework/packages/terra-layout/examples/Index.site-page';
import TerraFrameworkIndex9 from './node_modules/terra-framework/packages/terra-modal-manager/examples/Index.site-page';
import TerraFrameworkIndex10 from './node_modules/terra-framework/packages/terra-navigation-layout/examples/Index.site-page';
import TerraFrameworkIndex11 from './node_modules/terra-framework/packages/terra-navigation-side-menu/examples/Index.site-page';
import TerraFrameworkIndex12 from './node_modules/terra-framework/packages/terra-slide-panel-manager/examples/Index.site-page';
import TerraFrameworkIndex13 from './node_modules/terra-framework/packages/terra-theme-provider/examples/Index.site-page';


const componentConfig = {
  'terra-clinical': {
    name: 'Clinical',
    path: '/clinical',
    pages: [
      {
        name: 'Site',
        path: '/site',
        pages: [
          {
            name: 'Action Header',
            path: '/action-header',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex,
              },
            ],
          },
          {
            name: 'Application',
            path: '/application',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex1,
              },
            ],
          },
          {
            name: 'Detail View',
            path: '/detail-view',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex2,
              },
            ],
          },
          {
            name: 'Error View',
            path: '/error-view',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex3,
              },
            ],
          },
          {
            name: 'Header',
            path: '/header',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex4,
              },
            ],
          },
          {
            name: 'Item Collection',
            path: '/item-collection',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex5,
              },
            ],
          },
          {
            name: 'Item Display',
            path: '/item-display',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex6,
              },
            ],
          },
          {
            name: 'Item View',
            path: '/item-view',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex7,
              },
            ],
          },
          {
            name: 'Label Value View',
            path: '/label-value-view',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex8,
              },
            ],
          },
          {
            name: 'No Data View',
            path: '/no-data-view',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex9,
              },
            ],
          },
          {
            name: 'Onset Picker',
            path: '/onset-picker',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraClinicalIndex10,
              },
            ],
          },
        ],
      },
    ],
  },
  'terra-core': {
    name: 'Core',
    path: '/core',
    pages: [
      {
        name: 'Site',
        path: '/site',
        pages: [
          {
            name: 'Alert',
            path: '/alert',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex,
              },
            ],
          },
          {
            name: 'Arrange',
            path: '/arrange',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex1,
              },
            ],
          },
          {
            name: 'Badge',
            path: '/badge',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex2,
              },
            ],
          },
          {
            name: 'Base',
            path: '/base',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex3,
              },
            ],
          },
          {
            name: 'Button Group',
            path: '/button-group',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex4,
              },
            ],
          },
          {
            name: 'Button',
            path: '/button',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex5,
              },
            ],
          },
          {
            name: 'Card',
            path: '/card',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex6,
              },
            ],
          },
          {
            name: 'Collapsible Menu View',
            path: '/collapsible-menu-view',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex7,
              },
            ],
          },
          {
            name: 'Content Container',
            path: '/content-container',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex8,
              },
            ],
          },
          {
            name: 'Date Picker',
            path: '/date-picker',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex9,
              },
            ],
          },
          {
            name: 'Date Time Picker',
            path: '/date-time-picker',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex10,
              },
            ],
          },
          {
            name: 'Demographics Banner',
            path: '/demographics-banner',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex11,
              },
            ],
          },
          {
            name: 'Dialog',
            path: '/dialog',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex12,
              },
            ],
          },
          {
            name: 'Divider',
            path: '/divider',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex13,
              },
            ],
          },
          {
            name: 'Dynamic Grid',
            path: '/dynamic-grid',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex14,
              },
            ],
          },
          {
            name: 'Embedded Content Consumer',
            path: '/embedded-content-consumer',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex15,
              },
            ],
          },
          {
            name: 'Form Checkbox',
            path: '/form-checkbox',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex16,
              },
            ],
          },
          {
            name: 'Form Field',
            path: '/form-field',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex17,
              },
            ],
          },
          {
            name: 'Form Input',
            path: '/form-input',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex18,
              },
            ],
          },
          {
            name: 'Form Radio',
            path: '/form-radio',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex19,
              },
            ],
          },
          {
            name: 'Form Select',
            path: '/form-select',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex20,
              },
            ],
          },
          {
            name: 'Form Textarea',
            path: '/form-textarea',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex21,
              },
            ],
          },
          {
            name: 'Form',
            path: '/form',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex22,
              },
            ],
          },
          {
            name: 'Grid',
            path: '/grid',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex23,
              },
            ],
          },
          {
            name: 'Heading',
            path: '/heading',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex24,
              },
            ],
          },
          {
            name: 'Hookshot',
            path: '/hookshot',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex25,
              },
            ],
          },
          {
            name: 'I 18 N',
            path: '/i-18-n',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex26,
              },
            ],
          },
          {
            name: 'Icon',
            path: '/icon',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex27,
              },
            ],
          },
          {
            name: 'Image',
            path: '/image',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex28,
              },
            ],
          },
          {
            name: 'List',
            path: '/list',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex29,
              },
            ],
          },
          {
            name: 'Menu',
            path: '/menu',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex30,
              },
            ],
          },
          {
            name: 'Modal',
            path: '/modal',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex31,
              },
            ],
          },
          {
            name: 'Overlay',
            path: '/overlay',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex32,
              },
            ],
          },
          {
            name: 'Popup',
            path: '/popup',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex33,
              },
            ],
          },
          {
            name: 'Profile Image',
            path: '/profile-image',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex34,
              },
            ],
          },
          {
            name: 'Progress Bar',
            path: '/progress-bar',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex35,
              },
            ],
          },
          {
            name: 'Responsive Element',
            path: '/responsive-element',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex36,
              },
            ],
          },
          {
            name: 'Search Field',
            path: '/search-field',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex37,
              },
            ],
          },
          {
            name: 'Signature',
            path: '/signature',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex38,
              },
            ],
          },
          {
            name: 'Slide Group',
            path: '/slide-group',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex39,
              },
            ],
          },
          {
            name: 'Slide Panel',
            path: '/slide-panel',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex40,
              },
            ],
          },
          {
            name: 'Spacer',
            path: '/spacer',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex41,
              },
            ],
          },
          {
            name: 'Status View',
            path: '/status-view',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex42,
              },
            ],
          },
          {
            name: 'Status',
            path: '/status',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex43,
              },
            ],
          },
          {
            name: 'Table',
            path: '/table',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex44,
              },
            ],
          },
          {
            name: 'Tabs',
            path: '/tabs',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex45,
              },
            ],
          },
          {
            name: 'Text',
            path: '/text',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex46,
              },
            ],
          },
          {
            name: 'Time Input',
            path: '/time-input',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex47,
              },
            ],
          },
          {
            name: 'Toggle Button',
            path: '/toggle-button',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex48,
              },
            ],
          },
          {
            name: 'Toggle',
            path: '/toggle',
            pages: [
              {
                name: 'Index',
                path: '/index',
                component: TerraCoreIndex49,
              },
            ],
          },
        ],
      },
    ],
  },
  'terra-framework': {
    name: 'Framework',
    path: '/framework',
    pages: [
      {
        name: 'Aggregator',
        path: '/aggregator',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex,
          },
        ],
      },
      {
        name: 'App Delegate',
        path: '/app-delegate',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex1,
          },
        ],
      },
      {
        name: 'Application Header Layout',
        path: '/application-header-layout',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex2,
          },
        ],
      },
      {
        name: 'Application Links',
        path: '/application-links',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex3,
          },
        ],
      },
      {
        name: 'Application Menu Layout',
        path: '/application-menu-layout',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex4,
          },
        ],
      },
      {
        name: 'Application Name',
        path: '/application-name',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex5,
          },
        ],
      },
      {
        name: 'Disclosure Manager',
        path: '/disclosure-manager',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex6,
          },
        ],
      },
      {
        name: 'Layout',
        path: '/layout',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex8,
          },
        ],
      },
      {
        name: 'Modal Manager',
        path: '/modal-manager',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex9,
          },
        ],
      },
      {
        name: 'Navigation Layout',
        path: '/navigation-layout',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex10,
          },
        ],
      },
      {
        name: 'Navigation Side Menu',
        path: '/navigation-side-menu',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex11,
          },
        ],
      },
      {
        name: 'Slide Panel Manager',
        path: '/slide-panel-manager',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex12,
          },
        ],
      },
      {
        name: 'Theme Provider',
        path: '/theme-provider',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraFrameworkIndex13,
          },
        ],
      },
    ],
  },
};

export default componentConfig;
