Rails.application.routes.draw do
  root to: 'components#index'

  get 'components', to: 'components#index'
  get 'components/core/arrange', to: 'terra_arrange#index'
  get 'components/core/base', to: 'terra_base#index'
  get 'components/core/badge', to: 'terra_badge#index'
  get 'components/core/button', to: 'terra_button#index'
  get 'components/core/button-group', to: 'terra_button_group#index'
  get 'components/core/content', to: 'terra_content#index'
  get 'components/core/content-container', to: 'terra_content_container#index'
  get 'components/core/date-picker', to: 'terra_date_picker#index'
  get 'components/core/demographics-banner', to: 'terra_demographics_banner#index'
  get 'components/core/form', to: 'terra_form#index'
  get 'components/core/grid', to: 'terra_grid#index'
  get 'components/core/i18n', to: 'terra_i18n#index'
  get 'components/core/icon', to: 'terra_icon#index'
  get 'components/core/image', to: 'terra_image#index'
  get 'components/core/list', to: 'terra_list#index'
  get 'components/core/modal', to: 'terra_modal#index'
  get 'components/core/progress-bar', to: 'terra_progress_bar#index'
  get 'components/core/responsive-element', to: 'terra_responsive_element#index'
  get 'components/core/slide-panel', to: 'terra_slide_panel#index'
  get 'components/core/standout', to: 'terra_standout#index'
  get 'components/core/status', to: 'terra_status#index'
  get 'components/core/table', to: 'terra_table#index'
  get 'components/core/title', to: 'terra_title#index'
end
